apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-api
  labels:
    app: storage-api
    k8s-app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-api
  template:
    metadata:
      labels:
        app: storage-api
        k8s-app: prometheus
    spec:
      containers:
      - name: storage-api
        image: dreamstream/storageapi:V7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://*:80"
        volumeMounts:
        - name: file-storage
          mountPath: /mnt/data
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: storage-api-claim
      nodeSelector:
        kubernetes.io/arch: amd64
      # Comment the following tolerations if Dashboard must not be deployed on master
      tolerations:
        - key: kubernetes.io/arch
          operator: Equal
          value: amd64
          effect: NoSchedule
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: storage-api-claim
  spec:
    storageClassName: storage-api-storage-class
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 3Gi