apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-api-pv
  labels:
    type: local
spec:
  storageClassName: storage-api-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"