apiVersion: v1
kind: Service
metadata:
  name: storage-api
  labels:
    app: storage-api
    k8s-app: prometheus
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: storage-api
  type: ClusterIP